---
jupyter: python3
---

```{python}
%load_ext autoreload
%autoreload 2
```

After storing the information about each datatype into a .json file, we flattened the .json files into pandas dataframes. Then, we read the utilities data into a pandas dataframe and created a joint dataframe between each weather datatype and the utility information to make it easier to plot.

```{python}
import pandas as pd
from functions import flatten_json, join_dataframes

df_avg_temp = flatten_json("TAVG")
df_total_prcp = flatten_json("PRCP")
df_avg_wind = flatten_json("AWND")
df_util = pd.read_csv("./data/electricity_FY13_23.csv")

df_util_wind = join_dataframes(df_avg_wind, df_util)
df_util_temp = join_dataframes(df_avg_temp, df_util)
df_util_prcp = join_dataframes(df_total_prcp, df_util)

print(df_util_prcp)
```

Now we can plot each weather datatype against the total monthly consumption (kwh) of Olin.  

```{python}
import functions
import matplotlib.pyplot as plt

functions.plot_weather_util_2_plots(df_util_temp)
functions.plot_weather_util_2_plots(df_util_prcp)
functions.plot_weather_util_2_plots(df_util_wind)
```

From these graphs, we can see that average temperature had a high positive correlation with electricy consumption, while wind speed had a slightly negative correlation with consumption. The reason why temperature is correlated with electricity consumption is fairly self-explanatory-- we use more AC in the summer and turn it off in the winter-- but the reason why wind speed would is correlated is not as intuitive. We further graphed wind speed against average temperature and saw that wind speed is slightly negatively correlated with temperature, revealing the reason why electricity consumption would be negatively correlated with wind speed.

```{python}
import matplotlib.pyplot as plt
import numpy as np
avg_temp = df_util_temp["value"]
avg_wind = df_util_wind["value"]
plt.scatter(avg_temp, avg_wind, color="red")
plt.xlabel("Average Temperature (F°)")
plt.ylabel("Average Wind Speed (mph)")
plt.title("Average Wind Speed vs Average Temperature")

z = np.polyfit(avg_temp, avg_wind, 1)
p = np.poly1d(z)
plt.plot(avg_temp, p(avg_temp), color="blue")

plt.show()
```

Going back to average temperature, we further created box plots to show the consumption for each of the seasons. The seasons were sorted on month, with December - Feburary being winter, March - May being spring, June - August being summer, and September - November being fall. This graph further supports our proposed reasoning of the correlation between temperature and consumption being because we turn off the AC in the winter and use it more in the summer.

```{python}
from functions import filter_season
SEASON_NAMES = ["Winter", "Spring", "Summer", "Fall"]

season_dfs = []
for season in SEASON_NAMES:
    df = filter_season(season, df_util_temp)
    season_dfs.append(df.reset_index())

season_data = []
for df in season_dfs:
    season_data.append(df["Total Cons. (kwh)"])

plt.boxplot(season_data, labels=SEASON_NAMES)
plt.ylabel("Total Energy Consumption (kwh)")
plt.title("Total Energy Consumption in each Season (kwh)")
plt.show()
```

